<?php
return [
    '1'   => [],
    '2'   => [],
    '3'   => [],
    '4'   => [],
    '5'   => [],
    '6'   => [
        '/api/admin/v1/telco/add',
        '/api/admin/v1/telco/info',
        '/api/admin/v1/telco/query',
        '/api/admin/v1/telco/delete',
        '/api/admin/v1/telco/modify',
        '/api/admin/v1/telco/detail',
        '/api/admin/v1/telco/enable',
        '/api/admin/v1/telco/disable',
        '/api/admin/v1/telco/login/create',
        '/api/admin/v1/telco/addLevel',
        '/api/admin/v1/telco/modifyLevel',
        '/api/admin/v1/telco/deleteLevel',
        '/api/admin/v1/telco/queryLevels',
        '/api/admin/v1/telco/detailLevel',
    ],
    '2-1' => [
        '/api/admin/v1/ads/top',
        '/api/admin/v1/ads/add',
        '/api/admin/v1/ads/type',
        '/api/admin/v1/ads/order',
        '/api/admin/v1/ads/query',
        '/api/admin/v1/ads/delete',
        '/api/admin/v1/ads/online',
        '/api/admin/v1/ads/detail',
        '/api/admin/v1/ads/modify',
        '/api/admin/v1/ads/addType',
    ],
    '2-2' => [
        '/api/admin/v1/recommends/add',
        '/api/admin/v1/recommends/all',
        '/api/admin/v1/recommends/top',
        '/api/admin/v1/recommends/query',
        '/api/admin/v1/recommends/order',
        '/api/admin/v1/recommends/modify',
        '/api/admin/v1/recommends/detail',
        '/api/admin/v1/recommends/update',
        '/api/admin/v1/recommends/delete',
        '/api/admin/v1/product/info/all',
        '/api/admin/v1/telco/allLevel',
    ],
    '3-1' => [
        '/api/admin/v1/product/info/add',
        '/api/admin/v1/product/info/query',
        '/api/admin/v1/product/info/query',
        '/api/admin/v1/product/info/modify',
        '/api/admin/v1/product/info/delete',
        '/api/admin/v1/product/info/online',
        '/api/admin/v1/product/info/detail',
        '/api/admin/v1/product/info/offline',
    ],
    '3-2' => [
        '/api/admin/v1/product/category/add',
        '/api/admin/v1/product/category/top',
        '/api/admin/v1/product/category/query',
        '/api/admin/v1/product/category/delete',
        '/api/admin/v1/product/category/detail',
        '/api/admin/v1/product/category/modify',
        '/api/admin/v1/product/category/update',
        '/api/admin/v1/product/category/ascend',
        '/api/admin/v1/product/category/descend',
    ],
    '4-1' => [
        '/api/admin/v1/right/add',
        '/api/admin/v1/right/all',
        '/api/admin/v1/right/query',
        '/api/admin/v1/right/detail',
        '/api/admin/v1/right/delete',
        '/api/admin/v1/right/modify',
        '/api/admin/v1/right/online',
        '/api/admin/v1/right/offline',
    ],
    '4-2' => [
    ],
    '5-1' => [
        '/api/admin/v1/account/add',
        '/api/admin/v1/account/start',
        '/api/admin/v1/account/query',
        '/api/admin/v1/account/delete',
        '/api/admin/v1/account/detail',
        '/api/admin/v1/account/modify',
        '/api/admin/v1/account/resetPwd',
    ],
    '5-2' => [
        '/api/admin/v1/role/add',
        '/api/admin/v1/role/query',
        '/api/admin/v1/role/modify',
        '/api/admin/v1/role/update',
        '/api/admin/v1/role/delete',
        '/api/admin/v1/role/detail',
        '/api/admin/v1/role/permission',
    ],
];
